### ISSUE TITLE
400 bad request when trying to login with special chars (dockerhub)

### ISSUE THREAD

**Issue by rfvgyhn** [christian-korneck/docker-pushrm#11]
**Describe the problem or bug**
I was getting a 400 result when trying to login to docker hub before changing my password. It was a randomly generated password so I don't remember it exactly, but it did have the following special chars
```
" ' : ` \ < >
```
After I changed my password, pushrm worked as expected.

**docker-pushrm version**
1.5.0

**Docker CLI version and platform**
19.03.13-ce
Arch Linux

**debug output**
```
DEBU Dockerhub.Pushrm called
DEBU retrieve Dockerhub jwt token, status code: 400
DEBU error retrieving Dockerhub jwt token, bad status code for response: 400 Bad Request
ERRO error trying to get a JWT token from Dockerhub for the stored Docker login. Try "docker logout" and "docker login". Also, if you have 2FA auth enabled in Dockerhub you'll need to disable it for this tool to work. (This is an unfortunate Dockerhub limitation, see docs for more infos).
```

**Additional context**
I was able to get a successful response with the old password via calling the API myself (with httpie). Perhaps some chars aren't being escaped properly?

**Comment by christian-korneck** [comment]
hi @Rfvgyhn , thanks for reporting this bug. Fixed in [v1.5.1](https://github.com/christian-korneck/docker-pushrm/releases/tag/v1.5.1).
