### ISSUE TITLE
False positive from Virus Total

### ISSUE THREAD

**Issue by AntonKrug** [christian-korneck/docker-pushrm#14]
**Describe the problem or bug**
Uploading the binary to virus total flags by some antivirus as unsafe, would it be worth messaging the scanning providers to get the tool excluded and not throw false positives?

https://www.virustotal.com/gui/file/403436d05702b04759a81fd80131a9acf9691ac86406c8764ebe4f1cc9554043/detection

**docker-pushrm version**
1.7.0 (windows 64-bit)

**Comment by christian-korneck** [comment]
@AntonKrug Thanks a lot, wasn't aware of this. I'm not sure if it's easy to fix the virustotal rating. Even a simple Golang hello-world program seems to produce false positives. I also quickly checked official builds of some well known Golang projects on virustotal (i.e. `docker.exe` from nightly builds, `containerd.exe`, etc) and they had false positives, too.

Removing upx compression for the windows binaries would reduce the false positives (windows/386: from ca. 10 to 5, windows/amd64: from ca 2 to 1).

Any more ideas would be welcome.

**Comment by christian-korneck** [comment]
I guess code signing would improve things (i.e. looking at hashicorp windows executables they're EV signed and have perfect virustotal rating). EV is only possible for orgs. I'll consider signing with a regular cert.

**Comment by christian-korneck** [comment]
The Windows binaries for [v1.7.0](https://github.com/christian-korneck/docker-pushrm/releases/tag/v1.7.0) are now codesigned and I've also removed the upx compression. This together gives a perfect score on virustotal.com. (Reports: [64](https://www.virustotal.com/gui/file/f66e25dca768f0abc895015b3fec165ef3cf8fc64ee8675546cc5ca3d26d6123/detection) / [32](https://www.virustotal.com/gui/file/0c0059e39f2627e0ea28ad50e0d88eedc8bb878883f4bf95fe2027db52207c7d/detection) bit)

The Windows code signing is currently a manual process (as it involves a hsm device), so I can't promise that I'll do it in time for every future release.

(Note for anyone ending up here in the future: If the release that you want to use isn't signed and this is a problem for you, please open an issue).
