### ISSUE TITLE
I get an Invalid Plugin, permission denied error message

### ISSUE THREAD

**Issue by eggbean** [christian-korneck/docker-pushrm#17]
I have downloaded the amd64 version and put it in `/usr/local/lib/docker/cli-plugins` but I get this error message after `docker pushrm --help`. Owner is root.
```
$ docker pushrm --help

Invalid Plugins:
  pushrm      failed to fetch metadata: fork/exec /usr/local/lib/docker/cli-plugins/docker-pushrm: permission denied
```
When using `$HOME/.docker/cli-plugins/docker-pushrm` instead, nothing different from normal happens at all.

I've not used docker plugins before, but I can't see anything that I am doing wrong.

**Comment by eggbean** [comment]
Just as I posted this I realised that I am using the darwin binary and I am not using a Mac. Embarrassing.

**Comment by eggbean** [comment]
At first, I was using the Darwin binary on Linux by accident, but the same thing happens with the amd64 Linux binary. And yes, I am using 64-bit Linux on ThinkPad laptop with Intel x86_64 CPU.

**Comment by christian-korneck** [comment]
what Linux distro and distro version are you using? (i.e. Fedora 35, Ubuntu 21.10, etc). What's your Docker version and how did you install Docker (i.e. distro package manager, https://get.docker.com/ , etc)?

**Comment by eggbean** [comment]
**docker-pushrm version**
v1.8.0 Linux amd64

**Docker CLI version and platform**
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:34 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**exact command that you're running**
$ docker pushrm --help

I'm using Pop!_OS 21.04 (based on Ubuntu 21.04

Docker was installed through the Docker repository using these instructions https://docs.docker.com/engine/install/ubuntu/

**Comment by eggbean** [comment]
I've just tried the same on a Debian 9.13 server using `/usr/local/lib/docker/cli-plugins` as location and get the same error and then I put it at `$HOME/.docker/cli-plugins/docker-pushrm` the same thing happens, which is nothing at all, not even an error.

**Comment by christian-korneck** [comment]
I just tried on Debian 11 (see below) and it worked. (Haven't tried on Pop!_OS yet). Couple of things:
- is the downloaded file valid / not corrupted? (i.e. downloading with `curl` without `-L` (follow redirects) might lead to a corrupted file)
- is the file `docker-pushrm` executable for all users? (`chmod a+rx <file>`)
- are you using the correct system-wide (`libexec`) path? Exact path varies depending on the distro
- are you sure no execution prevention like apparmor, selinux is interfering?

so this works for me on a vanilla Debian 11 VM (from digitalocean cloud):

install latest Docker:
```
$ curl -L https://get.docker.com > get_docker.sh && chmod +x get_docker.sh
$ ./get_docker.sh
$ systemctl enable --now docker
$ docker --version
Docker version 20.10.12, build e91ed57
```

try plugin in user home dir (`$HOME/.docker/cli-plugins`):
```
$ mkdir -p $HOME/.docker/cli-plugins
$ curl -L https://github.com/christian-korneck/docker-pushrm/releases/download/v1.8.0/docker-pushrm_linux_amd64 -o $HOME/.docker/cli-plugins/docker-pushrm
$ chmod +x $HOME/.docker/cli-plugins/docker-pushrm
$ docker --help | grep -i pushrm
  pushrm*     Push Readme to container registry (Christian Korneck, 1.8.0)

# works!
```

alternatively try in system wide plugin dir:
```
# find dir (exact path varies depending on Linux distro)
$ locate cli-plugins
/root/.docker/cli-plugins
/usr/libexec/docker/cli-plugins
# move plugin from home to system:
$ mv $HOME/.docker/cli-plugins/docker-pushrm /usr/libexec/docker/cli-plugins/
# set permissions for all users:
$ chmod a+rx /usr/libexec/docker/cli-plugins/docker-pushrm
$ docker --help | grep -i pushrm
  pushrm*     Push Readme to container registry (Christian Korneck, 1.8.0)
# works!
```

**Comment by eggbean** [comment]
Thanks for your help. I got it working now, using the right directory location. It also works in the one I had been using, now that I made it executable. I had made it executable before, so I think what I must have done was not had the right owner set while not having it set for all users. Or something like that. Cheers.
