### ISSUE TITLE
incorrect copy of README.md uploaded

### ISSUE THREAD

**Issue by aendie** [christian-korneck/docker-pushrm#19]
This is a minor issue (in Release 1.8.0)...

I noticed (when running on Windows) that if I have two copies of a readme file, e.g.

```
README - OLD.md
README.md
```
then the 'OLD' copy is uploaded. My intention was to retain some text until a problem is fixed and `README.md` is the modified version (valid until the bug is fixed).

The workaround is easy ... move `README - OLD.md` to another folder.

**Compliments on your program - it is very useful!**

**Comment by christian-korneck** [comment]
thanks, I'll have a look.

**Comment by christian-korneck** [comment]
Should be fixed now in [v1.8.1](https://github.com/christian-korneck/docker-pushrm/releases/tag/v1.8.1). Thanks again for reporting this!

For reference, the auto search order when no specific file is stated with `--file`:
- `README-containers.md` (case sensitive)
- `README.md` (case sensitive)
- fuzzy fallback to the first match of a file with prefix `README` (case insensitive) - no guarantees on order here if multiple matching files are present
