### ISSUE TITLE
Strange usage line

### ISSUE THREAD

**Issue by mitar** [christian-korneck/docker-pushrm#2]
In help, I see:

```
Usage:
  docker-pushrm  NAME[:TAG] [flags]
```

But that is not really used, useful, or needed?

**Comment by christian-korneck** [comment]
correct, none of the current providers (dockerhub, quay, harbor2) offers READMEs per tag (only per repo). However, I've added this intentionally in case that a registry adds support of this at some point in the future. (I'm thinking about maybe writing a lightweight container registry with this feature myself in the (distant) future). Having this from the beginning avoids making a breaking change to the CLI interface later.

If you don't define a tag it's defaulting to `latest`.

**Comment by mitar** [comment]
OK, but then higher up in another text you should also mention the tag, because there it is just `IMAGE`. So make it then consistent. :-)

**Comment by christian-korneck** [comment]
fixed in [v1.0.2](https://github.com/christian-korneck/docker-pushrm/releases/tag/v1.0.2)

**Comment by mitar** [comment]
Awesome, thanks!
