### ISSUE TITLE
Support Docker Plugin Install

### ISSUE THREAD

**Issue by ProfessorManhattan** [christian-korneck/docker-pushrm#22]
Hey, is there a way to leverage `docker plugin install` to install this? If not, could you possibly add support for this?

**Comment by christian-korneck** [comment]
I believe `docker plugin install` doesn't support CLI plugins.

An alternative might be bringing this tool to the various package managers / OS distros. Contributions welcome. (I saw folks from the community have put it on scoop (Windows package manager) and created an Arch Linux package. But there are so many more to do, i.e. Ubuntu ppa, Fedora copr, Homebrew, etc).
