### ISSUE TITLE
Possibility to support robot account login for quay?

### ISSUE THREAD

**Issue by AliciaBytes** [christian-korneck/docker-pushrm#26]
**Describe the problem or bug**
I currently have 1 robot account per repository on quay.io and I would like to keep this separation of permission, but 1 separate robot account + 1 app for each repository will get a lot. Would it be possible to update the description with the robot account as alternative login method?

**Comment by christian-korneck** [comment]
I believe quay robot accounts can only do the Docker side of things ([docker registry api v2](https://docs.docker.com/registry/spec/api/)), but not use the quay api, which is required to update the repo description. So the best place for such a request ("allow quay robot users to update the repo description via quay api") would probably be the quay project.

Having said that, I haven't kept up with quay improvements for a while and will dobule check.

**Comment by christian-korneck** [comment]
> Having said that, I haven't kept up with quay improvements for a while and will dobule check.

just had a quick look and don't think it's possible to use the quay api with robot account credentials. Best to open an issue with the quay project (feel free to CC me).
