### ISSUE TITLE
Validation error “Exceeded max number of characters”

### ISSUE THREAD

**Issue by marvinruder** [christian-korneck/docker-pushrm#27]
**Describe the problem or bug**
When attempting to upload to Docker Hub, the request fails with the status code 400 and a message “Exceeded max number of characters”.

**docker-pushrm version**
1.9.0

**Docker CLI version and platform**
24.0.0 on Fedora CoreOS 38.20230430.3.1

**exact command that you're running**
example: `docker run --rm -t -v /tmp:/tmp -e DOCKER_USER=[username] -e DOCKER_PASS=[token] chko/docker-pushrm --file [filepath] marvinruder/rating-tracker --debug`

**debug output**
```
DEBU root cmd init config                         
DEBU home dir: /home                              
DEBU subcommand "pushrm" called                   
DEBU Using target: docker.io/marvinruder/rating-tracker:latest 
DEBU using README file: /tmp/jenkins-cache/README/c46bbe76 
DEBU server: docker.io                            
DEBU namespace: marvinruder                       
DEBU repo: rating-tracker                         
DEBU tag: latest                                  
DEBU repo provider: dockerhub                     
DEBU Dockerhub.GetAuthident called                
DEBU using credentials for user marvinruder from generic env var 
DEBU Using Docker creds: marvinruder ********     
DEBU Dockerhub.Pushrm called                      
DEBU retrieve Dockerhub jwt token, status code: 200 
DEBU push readme, response body: {"message":"httperror 400: request had 1 validation error","errinfo":{"fielderrors":{"full_description":"Exceeded max number of characters"}}} 
DEBU push README, status code: 400                
DEBU error pushing README, bad status code for response: 400 Bad Request 
ERRO error pushing readme to repo server. See error message below. Run with "--debug" for more details. 

error pushing README, bad status code for response: 400 Bad Request 
```

**Additional context**
Manually adding the entire README using a web browser ~works fine~ (see comment). The file is 26148 bytes long.

**Comment by marvinruder** [comment]
Closing as the bug also appears when manually uploading on the webpage (without any error message though, the new README is accepted and is shown immediately after, but reloading the page shows the old one again. Took me a moment to realize this.). Will report to Docker Hub instead (at least so that they handle errors properly).

**Comment by christian-korneck** [comment]
anyways thanks for the info, wasn't aware of it :)
