### ISSUE TITLE
Max characters allowed in README.md?

### ISSUE THREAD

**Issue by stacyhung** [christian-korneck/docker-pushrm#28]
I was trying to push a README to my docker repository with:

`docker pushrm {user}/{repo}`

the `--debug` version of the run produced the error message:

DEBU push readme, response body: {"message":"httperror 400: request had 1 validation error","errinfo":{"fielderrors":{"full_description":"Exceeded max number of characters"}}}

I'm using version 1.9.0 of the docker CLI plugin with docker 23.0.5, build bc4487a.

My README.md is quite long, so I'm wondering what is the maximum number of characters allowed?

**Comment by christian-korneck** [comment]
@stacyhung I believe Docker Hub's current maximum length for the repo description is exactly **25000 characters**.
If you have a very long README I'd recommend splitting it in multiple Markdown files and linking them with each other.

(As this is a limitation of Docker Hub and not the `docker-pushrm` tool, there's little we can do about it, unfortunately).

**Comment by stacyhung** [comment]
Thanks for the quick response!  Good to know.
