### ISSUE TITLE
Support also setting short description on Docker Hub

### ISSUE THREAD

**Issue by mitar** [christian-korneck/docker-pushrm#3]
There is also a short description on Docker Hub. It would be great if I could set that as well.

**Comment by christian-korneck** [comment]
this is a good idea, I'll keep this as a feature request for the next minor version

**Comment by christian-korneck** [comment]
> There is also a short description on Docker Hub. It would be great if I could set that as well.

@mitar : This is now possible in [v1.3.0](https://github.com/christian-korneck/docker-pushrm/releases/tag/v1.3.0).

Example:
```
docker pushrm --short "my short description" my-user/my-repo
```

**Comment by mitar** [comment]
Awesome!
